version: '3.8'

services:
  mysql-test:
    image: mysql:8.0
    container_name: php-mcp-mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: testroot
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "33306:3306"
    volumes:
      - ./tests/fixtures/test-data.sql:/docker-entrypoint-initdb.d/01-test-data.sql
      - mysql_test_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 10s
    tmpfs:
      - /tmp
      - /var/lib/mysql-files

volumes:
  mysql_test_data:
    driver: local